# nPM1300 fails to respond I2C requests, there's likely a bug in SF32LB52 Zephyr
# driver, as it works fine on PebbleOS. For now, disable the charger module as
# it is not critical anyway
CONFIG_PB_CHARGER=n
