# Copyright (c) 2025 Core Devices LLC
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: coredevices
      url-base: https://github.com/coredevices

  projects:
    - name: zephyr
      remote: coredevices
      revision: pblboot
      import:
        name-allowlist:
          - cmsis_6
          - hal_sifli
